package com.demo.model;
// Generated Mar 2, 2019 4:10:03 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Commentbugs generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "COMMENTBUGS", schema = "c##nguyenquan")
public class Commentbugs implements java.io.Serializable {

	private int idCm;
	private Bugs bugs;
	private Staff staff;
	private boolean status;

	public Commentbugs() {
	}

	public Commentbugs(int idCm, Bugs bugs, Staff staff, boolean status) {
		this.idCm = idCm;
		this.bugs = bugs;
		this.staff = staff;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "commentbugs_seq")
	@SequenceGenerator(name = "commentbugs_seq", sequenceName = "commentbugs_seq")
	@Column(name = "ID_CM", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdCm() {
		return this.idCm;
	}

	public void setIdCm(int idCm) {
		this.idCm = idCm;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_BUGS", nullable = false)
	public Bugs getBugs() {
		return this.bugs;
	}

	public void setBugs(Bugs bugs) {
		this.bugs = bugs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_STAFF", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Column(name = "STATUS", nullable = false, precision = 1, scale = 0)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
