package com.demo.model;
// Generated Mar 2, 2019 4:10:03 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Slide generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SLIDE", schema = "c##nguyenquan")
public class Slide implements java.io.Serializable {

	private int idSlide;
	private Staff staff;
	private String image;
	private String contentt;

	public Slide() {
	}

	public Slide(int idSlide, Staff staff, String image) {
		this.idSlide = idSlide;
		this.staff = staff;
		this.image = image;
	}
	
	
	public Slide(String contentt, String image, Staff staff) {
		super();
		this.staff = staff;
		this.image = image;
		this.contentt = contentt;
	}

	public Slide(int idSlide, Staff staff, String image, String contentt) {
		this.idSlide = idSlide;
		this.staff = staff;
		this.image = image;
		this.contentt = contentt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "slide_seq")
	@SequenceGenerator(name = "slide_seq", sequenceName = "slide_seq")
	@Column(name = "ID_SLIDE", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdSlide() {
		return this.idSlide;
	}

	public void setIdSlide(int idSlide) {
		this.idSlide = idSlide;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_STAFF", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Column(name = "IMAGE", nullable = false, length = 225)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "CONTENTT", length = 225)
	public String getContentt() {
		return this.contentt;
	}

	public void setContentt(String contentt) {
		this.contentt = contentt;
	}

}
