package com.demo.model;
// Generated Mar 2, 2019 4:10:03 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Staff generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "STAFF", schema = "c##nguyenquan")
public class Staff implements java.io.Serializable {

	private int idStaff;
	private Project project;
	private String username;
	private int roless;
	private Boolean status;
	private String names;
	private String email;
	private String phone;
	private String avatar;
	private String addrSky;
	private String addrFb;
	private String address;
	private int levelss;
	private String major;
	private String finishs;
	private String school;
	private Set<Commentbugs> commentbugses = new HashSet<Commentbugs>(0);
	private Set<Bugs> bugses = new HashSet<Bugs>(0);
	private Set<Timesheet> timesheets = new HashSet<Timesheet>(0);
	private Set<Request> requests = new HashSet<Request>(0);
	private Set<Slide> slides = new HashSet<Slide>(0);
	private Set<News> newses = new HashSet<News>(0);
	private Set<Reports> reports = new HashSet<Reports>(0);

	public Staff() {
	}

	public Staff(int idStaff, Project project, String username, int roless, String names, String email) {
		this.idStaff = idStaff;
		this.project = project;
		this.username = username;
		this.roless = roless;
		this.names = names;
		this.email = email;
	}

	public Staff(int idStaff, Project project, String username, int roless, Boolean status, String names,
			String email, String phone, String avatar, String addrSky, String addrFb, String address,
			int levelss, String major, String finishs, String school, Set<Commentbugs> commentbugses,
			Set<Bugs> bugses, Set<Timesheet> timesheets, Set<Request> requests, Set<Slide> slides, Set<News> newses , Set<Reports> reports) {
		this.idStaff = idStaff;
		this.project = project;
		this.username = username;
		this.roless = roless;
		this.status = status;
		this.names = names;
		this.email = email;
		this.phone = phone;
		this.avatar = avatar;
		this.addrSky = addrSky;
		this.addrFb = addrFb;
		this.address = address;
		this.levelss = levelss;
		this.major = major;
		this.finishs = finishs;
		this.school = school;
		this.commentbugses = commentbugses;
		this.bugses = bugses;
		this.timesheets = timesheets;
		this.requests = requests;
		this.slides = slides;
		this.newses = newses;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "staff_seq")
	@SequenceGenerator(name = "staff_seq", sequenceName = "staff_seq")
	@Column(name = "ID_STAFF", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdStaff() {
		return this.idStaff;
	}

	public void setIdStaff(int idStaff) {
		this.idStaff = idStaff;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PROJECT", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "USERNAME", nullable = false, length = 225)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ROLESS", nullable = false, precision = 22, scale = 0)
	public int getRoless() {
		return this.roless;
	}

	public void setRoless(int roless) {
		this.roless = roless;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "NAMES", nullable = false, length = 225)
	public String getNames() {
		return this.names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	@Column(name = "EMAIL", nullable = false, length = 225)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE", length = 225)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "AVATAR", length = 225)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "ADDR_SKY", length = 225)
	public String getAddrSky() {
		return this.addrSky;
	}

	public void setAddrSky(String addrSky) {
		this.addrSky = addrSky;
	}

	@Column(name = "ADDR_FB", length = 225)
	public String getAddrFb() {
		return this.addrFb;
	}

	public void setAddrFb(String addrFb) {
		this.addrFb = addrFb;
	}

	@Column(name = "ADDRESS", length = 225)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "LEVELSS", precision = 22, scale = 0)
	public int getLevelss() {
		return this.levelss;
	}

	public void setLevelss(int levelss) {
		this.levelss = levelss;
	}

	@Column(name = "MAJOR", length = 225)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "FINISHS", length = 225)
	public String getFinishs() {
		return this.finishs;
	}

	public void setFinishs(String finishs) {
		this.finishs = finishs;
	}

	@Column(name = "SCHOOL", length = 15)
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Commentbugs> getCommentbugses() {
		return this.commentbugses;
	}

	public void setCommentbugses(Set<Commentbugs> commentbugses) {
		this.commentbugses = commentbugses;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Bugs> getBugses() {
		return this.bugses;
	}

	public void setBugses(Set<Bugs> bugses) {
		this.bugses = bugses;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Timesheet> getTimesheets() {
		return this.timesheets;
	}

	public void setTimesheets(Set<Timesheet> timesheets) {
		this.timesheets = timesheets;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Request> getRequests() {
		return this.requests;
	}

	public void setRequests(Set<Request> requests) {
		this.requests = requests;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Slide> getSlides() {
		return this.slides;
	}

	public void setSlides(Set<Slide> slides) {
		this.slides = slides;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Reports> getReports() {
		return reports;
	}

	public void setReports(Set<Reports> reports) {
		this.reports = reports;
	}

	
}
